apiVersion: v1
kind: Template
parameters:
- name: APPLICATION_NAME
- name: TARGET_NAMESPACE
- name: OCPDOMAIN
metadata:
  name: ${APPLICATION_NAME}
objects:
# Route
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${APPLICATION_NAME}-${TARGET_NAMESPACE}.${OCPDOMAIN}
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-actuator
  spec:
    host: ${APPLICATION_NAME}-actuator-${TARGET_NAMESPACE}.${OCPDOMAIN}
    port:
      targetPort: 9090-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}