apiVersion: v1
kind: Template
metadata:
  labels:
    app: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      app-name-pipeline: ${APPLICATION_NAME}-${APPLICATION_PIPELINE}
      app-pipeline: ${APPLICATION_PIPELINE}
    name: ${APPLICATION_NAME}-${APPLICATION_PIPELINE}
  spec:
    replicas: 0
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}-${APPLICATION_PIPELINE}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 33%
        maxUnavailable: 0
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          app-name-pipeline: ${APPLICATION_NAME}-${APPLICATION_PIPELINE}
          app-pipeline: ${APPLICATION_PIPELINE}
          deploymentconfig: ${APPLICATION_NAME}-${APPLICATION_PIPELINE}
          env: ${ENV}
      spec:
        containers:
        - env:
          - name: JAVA_OPTIONS
            value: -Xms256m -Xmx256m -XX:-TieredCompilation -XX:TieredStopAtLevel=1 -Xss228k -XX:CompressedClassSpaceSize=25m
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/info
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 450
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
          name: ${APPLICATION_NAME}-${APPLICATION_PIPELINE}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 450
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
          - mountPath: /deployments/config/
            name: volume-${APPLICATION_NAME}-${APPLICATION_PIPELINE}
        volumes:
        - configMap:
            defaultMode: 420
            name: ${CONFIGMAP_NAME}
          name: volume-${APPLICATION_NAME}-${APPLICATION_PIPELINE}
    test: false
    triggers: []
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      app-name-pipeline: ${APPLICATION_NAME}-${APPLICATION_PIPELINE}
      app-pipeline: ${APPLICATION_PIPELINE}
    name: ${APPLICATION_NAME}-${APPLICATION_PIPELINE}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}-${APPLICATION_PIPELINE}
parameters:
- name: APPLICATION_NAME
- name: APPLICATION_PIPELINE
- name: AUTO_SCALE_MIN_REPLICAS
- name: AUTO_SCALE_MAX_REPLICAS
- name: OCPDOMAIN
- name: TAG
- name: TARGET_NAMESPACE
- name: CONFIGMAP_NAME
- name: ENV
- name: OPCO
- name: DOMAIN
- name: APP_TYPE
- name: REPLICAS
