spring.jersey.application-path=/
server.port=8080
spring.jackson.default-property-inclusion=non-null
spring.application.name=springboot-actuator
#
# Access logs:
logback.access.enabled=true
logback.access.url.pattern=/*
#
# Actuator properties:
management.port=9090
management.contextPath=/actuator
endpoints.enabled=false
management.endpoints.enabled-by-default=false
endpoints.sensitive=true
endpoints.health.enabled=true
endpoints.health.sensitive=false
endpoints.info.enabled=true
endpoints.info.sensitive=false
endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false
metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram[http.server.requests]=true
management.metrics.distribution.percentiles[http.server.requests]=0.95,0.99
info.app.name=springboot-actuator
info.app.description=springboot-actuator project for Spring Boot
#
#setting different log level
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.netflix.hystrix=ERROR
